/* Parsing tree 0*/
if (missing(feature_25) or feature_25 <= 1) then do;
    if (missing(feature_25) or feature_25 <= 0) then do;
        if (missing(feature_9) or feature_9 <= 1) then do;
            if (missing(feature_3) or feature_3 <= 1) then do;
                if (missing(feature_13) or feature_13 <= 1) then do;
                    treeValue0 = 0;
                end;
                else do;
                    treeValue0 = 0;
                end;
            end;
            else do;
                treeValue0 = 0;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                treeValue0 = 0;
            end;
            else do;
                treeValue0 = 0;
            end;
        end;
    end;
    else do;
        if (missing(feature_5) or feature_5 <= 0) then do;
            if (missing(feature_26) or feature_26 <= 0) then do;
                if (missing(feature_24) or feature_24 <= 0) then do;
                    treeValue0 = 0;
                end;
                else do;
                    treeValue0 = 0;
                end;
            end;
            else do;
                if (missing(feature_25) or feature_25 <= 0) then do;
                    if (missing(feature_27) or feature_27 <= 0) then do;
                        if (missing(feature_26) or feature_26 <= 0) then do;
                            if (missing(feature_27) or feature_27 <= 0) then do;
                                treeValue0 = 0;
                            end;
                            else do;
                                treeValue0 = 0;
                            end;
                        end;
                        else do;
                            treeValue0 = 0;
                        end;
                    end;
                    else do;
                        if (missing(feature_3) or feature_3 <= 1) then do;
                            treeValue0 = 0;
                        end;
                        else do;
                            treeValue0 = 0;
                        end;
                    end;
                end;
                else do;
                    treeValue0 = 0;
                end;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_26) or feature_26 <= 0) then do;
                    if (missing(feature_25) or feature_25 <= 0) then do;
                        treeValue0 = 0;
                    end;
                    else do;
                        if (missing(feature_0) or feature_0 <= 1) then do;
                            treeValue0 = 0;
                        end;
                        else do;
                            treeValue0 = 0;
                        end;
                    end;
                end;
                else do;
                    treeValue0 = 0;
                end;
            end;
            else do;
                if (missing(feature_0) or feature_0 <= 1) then do;
                    if (missing(feature_3) or feature_3 <= 2) then do;
                        if (missing(feature_25) or feature_25 <= 0) then do;
                            treeValue0 = 0;
                        end;
                        else do;
                            treeValue0 = 0;
                        end;
                    end;
                    else do;
                        treeValue0 = 0;
                    end;
                end;
                else do;
                    if (missing(feature_24) or feature_24 <= 1) then do;
                        treeValue0 = 0;
                    end;
                    else do;
                        if (missing(feature_24) or feature_24 <= 1) then do;
                            treeValue0 = 0;
                        end;
                        else do;
                            treeValue0 = 0;
                        end;
                    end;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_25) or feature_25 <= 1) then do;
        if (missing(feature_22) or feature_22 <= 1) then do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_5) or feature_5 <= 0) then do;
                    if (missing(feature_9) or feature_9 <= 0) then do;
                        treeValue0 = 0;
                    end;
                    else do;
                        if (missing(feature_10) or feature_10 <= 0) then do;
                            treeValue0 = 0;
                        end;
                        else do;
                            treeValue0 = 0;
                        end;
                    end;
                end;
                else do;
                    treeValue0 = 0;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 0) then do;
                    treeValue0 = 0;
                end;
                else do;
                    treeValue0 = 0;
                end;
            end;
        end;
        else do;
            treeValue0 = 0;
        end;
    end;
    else do;
        treeValue0 = 0;
    end;
end;

/* Parsing tree 1*/
if (missing(feature_25) or feature_25 <= 1) then do;
    if (missing(feature_25) or feature_25 <= 0) then do;
        if (missing(feature_9) or feature_9 <= 1) then do;
            if (missing(feature_13) or feature_13 <= 1) then do;
                if (missing(feature_24) or feature_24 <= 0) then do;
                    treeValue1 = 0;
                end;
                else do;
                    if (missing(feature_26) or feature_26 <= 0) then do;
                        treeValue1 = 0;
                    end;
                    else do;
                        if (missing(feature_22) or feature_22 <= 0) then do;
                            treeValue1 = 0;
                        end;
                        else do;
                            treeValue1 = 0;
                        end;
                    end;
                end;
            end;
            else do;
                treeValue1 = 0;
            end;
        end;
        else do;
            if (missing(feature_19) or feature_19 <= 1) then do;
                treeValue1 = 0;
            end;
            else do;
                treeValue1 = 0;
            end;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0) then do;
            if (missing(feature_5) or feature_5 <= 0) then do;
                if (missing(feature_14) or feature_14 <= 0) then do;
                    treeValue1 = 0;
                end;
                else do;
                    treeValue1 = 0;
                end;
            end;
            else do;
                if (missing(feature_6) or feature_6 <= 0) then do;
                    treeValue1 = 0;
                end;
                else do;
                    treeValue1 = 0;
                end;
            end;
        end;
        else do;
            if (missing(feature_26) or feature_26 <= 1) then do;
                if (missing(feature_5) or feature_5 <= 0) then do;
                    if (missing(feature_9) or feature_9 <= 1) then do;
                        if (missing(feature_3) or feature_3 <= 1) then do;
                            if (missing(feature_25) or feature_25 <= 0) then do;
                                if (missing(feature_26) or feature_26 <= 0) then do;
                                    treeValue1 = 0;
                                end;
                                else do;
                                    treeValue1 = 0;
                                end;
                            end;
                            else do;
                                treeValue1 = 0;
                            end;
                        end;
                        else do;
                            treeValue1 = 0;
                        end;
                    end;
                    else do;
                        treeValue1 = 0;
                    end;
                end;
                else do;
                    treeValue1 = 0;
                end;
            end;
            else do;
                if (missing(feature_3) or feature_3 <= 2) then do;
                    if (missing(feature_9) or feature_9 <= 1) then do;
                        treeValue1 = 0;
                    end;
                    else do;
                        treeValue1 = 0;
                    end;
                end;
                else do;
                    treeValue1 = 0;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_25) or feature_25 <= 1) then do;
        if (missing(feature_22) or feature_22 <= 1) then do;
            if (missing(feature_22) or feature_22 <= 0) then do;
                treeValue1 = 0;
            end;
            else do;
                if (missing(feature_24) or feature_24 <= 0) then do;
                    treeValue1 = 0;
                end;
                else do;
                    if (missing(feature_24) or feature_24 <= 0) then do;
                        if (missing(feature_26) or feature_26 <= 0) then do;
                            treeValue1 = 0;
                        end;
                        else do;
                            treeValue1 = 0;
                        end;
                    end;
                    else do;
                        treeValue1 = 0;
                    end;
                end;
            end;
        end;
        else do;
            if (missing(feature_24) or feature_24 <= 1) then do;
                if (missing(feature_2) or feature_2 <= 1) then do;
                    if (missing(feature_19) or feature_19 <= 1) then do;
                        if (missing(feature_3) or feature_3 <= 0) then do;
                            treeValue1 = 0;
                        end;
                        else do;
                            treeValue1 = 0;
                        end;
                    end;
                    else do;
                        treeValue1 = 0;
                    end;
                end;
                else do;
                    treeValue1 = 0;
                end;
            end;
            else do;
                treeValue1 = 0;
            end;
        end;
    end;
    else do;
        treeValue1 = 0;
    end;
end;

/* Parsing tree 2*/
if (missing(feature_27) or feature_27 <= 0) then do;
    if (missing(feature_26) or feature_26 <= 0) then do;
        if (missing(feature_5) or feature_5 <= 0) then do;
            if (missing(feature_0) or feature_0 <= 1) then do;
                if (missing(feature_9) or feature_9 <= 1) then do;
                    treeValue2 = 0;
                end;
                else do;
                    treeValue2 = 0;
                end;
            end;
            else do;
                treeValue2 = 0;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_2) or feature_2 <= -1) then do;
                    treeValue2 = 0;
                end;
                else do;
                    treeValue2 = 0;
                end;
            end;
            else do;
                treeValue2 = 0;
            end;
        end;
    end;
    else do;
        if (missing(feature_5) or feature_5 <= 0) then do;
            if (missing(feature_22) or feature_22 <= 1) then do;
                if (missing(feature_27) or feature_27 <= 0) then do;
                    if (missing(feature_26) or feature_26 <= 0) then do;
                        treeValue2 = 0;
                    end;
                    else do;
                        if (missing(feature_0) or feature_0 <= 0) then do;
                            treeValue2 = 0;
                        end;
                        else do;
                            treeValue2 = 0;
                        end;
                    end;
                end;
                else do;
                    if (missing(feature_26) or feature_26 <= 0) then do;
                        treeValue2 = 0;
                    end;
                    else do;
                        if (missing(feature_24) or feature_24 <= 1) then do;
                            treeValue2 = 0;
                        end;
                        else do;
                            treeValue2 = 0;
                        end;
                    end;
                end;
            end;
            else do;
                treeValue2 = 0;
            end;
        end;
        else do;
            treeValue2 = 0;
        end;
    end;
end;
else do;
    if (missing(feature_22) or feature_22 <= 1) then do;
        if (missing(feature_24) or feature_24 <= 1) then do;
            if (missing(feature_27) or feature_27 <= 1) then do;
                treeValue2 = 0;
            end;
            else do;
                treeValue2 = 0;
            end;
        end;
        else do;
            if (missing(feature_22) or feature_22 <= 0) then do;
                treeValue2 = 0;
            end;
            else do;
                if (missing(feature_3) or feature_3 <= 1) then do;
                    treeValue2 = 0;
                end;
                else do;
                    if (missing(feature_2) or feature_2 <= 0) then do;
                        treeValue2 = 0;
                    end;
                    else do;
                        treeValue2 = 0;
                    end;
                end;
            end;
        end;
    end;
    else do;
        if (missing(feature_27) or feature_27 <= 1) then do;
            if (missing(feature_5) or feature_5 <= 1) then do;
                if (missing(feature_6) or feature_6 <= -1) then do;
                    treeValue2 = 0;
                end;
                else do;
                    if (missing(feature_6) or feature_6 <= 1) then do;
                        treeValue2 = 0;
                    end;
                    else do;
                        treeValue2 = 0;
                    end;
                end;
            end;
            else do;
                treeValue2 = 0;
            end;
        end;
        else do;
            if (missing(feature_3) or feature_3 <= 2) then do;
                if (missing(feature_8) or feature_8 <= 0) then do;
                    if (missing(feature_5) or feature_5 <= 1) then do;
                        if (missing(feature_23) or feature_23 <= 0) then do;
                            treeValue2 = 0;
                        end;
                        else do;
                            treeValue2 = 0;
                        end;
                    end;
                    else do;
                        treeValue2 = 0;
                    end;
                end;
                else do;
                    if (missing(feature_24) or feature_24 <= 1) then do;
                        if (missing(feature_24) or feature_24 <= 0) then do;
                            treeValue2 = 0;
                        end;
                        else do;
                            treeValue2 = 0;
                        end;
                    end;
                    else do;
                        treeValue2 = 0;
                    end;
                end;
            end;
            else do;
                treeValue2 = 0;
            end;
        end;
    end;
end;

/* Parsing tree 3*/
if (missing(feature_25) or feature_25 <= 1) then do;
    if (missing(feature_25) or feature_25 <= 0) then do;
        if (missing(feature_9) or feature_9 <= 1) then do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_0) or feature_0 <= 0) then do;
                    if (missing(feature_9) or feature_9 <= 0) then do;
                        treeValue3 = 0;
                    end;
                    else do;
                        if (missing(feature_17) or feature_17 <= 1) then do;
                            treeValue3 = 0;
                        end;
                        else do;
                            treeValue3 = 0;
                        end;
                    end;
                end;
                else do;
                    treeValue3 = 0;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 1) then do;
                    treeValue3 = 0;
                end;
                else do;
                    treeValue3 = 0;
                end;
            end;
        end;
        else do;
            treeValue3 = 0;
        end;
    end;
    else do;
        if (missing(feature_5) or feature_5 <= 0) then do;
            if (missing(feature_26) or feature_26 <= 0) then do;
                if (missing(feature_24) or feature_24 <= 0) then do;
                    treeValue3 = 0;
                end;
                else do;
                    treeValue3 = 0;
                end;
            end;
            else do;
                if (missing(feature_25) or feature_25 <= 0) then do;
                    if (missing(feature_27) or feature_27 <= 0) then do;
                        treeValue3 = 0;
                    end;
                    else do;
                        if (missing(feature_9) or feature_9 <= 1) then do;
                            if (missing(feature_1) or feature_1 <= 1) then do;
                                treeValue3 = 0;
                            end;
                            else do;
                                treeValue3 = 0;
                            end;
                        end;
                        else do;
                            treeValue3 = 0;
                        end;
                    end;
                end;
                else do;
                    if (missing(feature_9) or feature_9 <= 1) then do;
                        treeValue3 = 0;
                    end;
                    else do;
                        treeValue3 = 0;
                    end;
                end;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_26) or feature_26 <= 0) then do;
                    if (missing(feature_25) or feature_25 <= 0) then do;
                        treeValue3 = 0;
                    end;
                    else do;
                        treeValue3 = 0;
                    end;
                end;
                else do;
                    treeValue3 = 0;
                end;
            end;
            else do;
                if (missing(feature_0) or feature_0 <= 1) then do;
                    if (missing(feature_3) or feature_3 <= 2) then do;
                        if (missing(feature_25) or feature_25 <= 0) then do;
                            treeValue3 = 0;
                        end;
                        else do;
                            treeValue3 = 0;
                        end;
                    end;
                    else do;
                        treeValue3 = 0;
                    end;
                end;
                else do;
                    if (missing(feature_6) or feature_6 <= 1) then do;
                        if (missing(feature_24) or feature_24 <= 1) then do;
                            treeValue3 = 0;
                        end;
                        else do;
                            treeValue3 = 0;
                        end;
                    end;
                    else do;
                        treeValue3 = 0;
                    end;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_3) or feature_3 <= 1) then do;
        if (missing(feature_24) or feature_24 <= 1) then do;
            if (missing(feature_27) or feature_27 <= 1) then do;
                if (missing(feature_15) or feature_15 <= -1) then do;
                    treeValue3 = 0;
                end;
                else do;
                    if (missing(feature_22) or feature_22 <= 1) then do;
                        treeValue3 = 0;
                    end;
                    else do;
                        treeValue3 = 0;
                    end;
                end;
            end;
            else do;
                treeValue3 = 0;
            end;
        end;
        else do;
            if (missing(feature_17) or feature_17 <= 1) then do;
                treeValue3 = 0;
            end;
            else do;
                treeValue3 = 0;
            end;
        end;
    end;
    else do;
        treeValue3 = 0;
    end;
end;

/* Parsing tree 4*/
if (missing(feature_25) or feature_25 <= 1) then do;
    if (missing(feature_25) or feature_25 <= 0) then do;
        if (missing(feature_9) or feature_9 <= 1) then do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_26) or feature_26 <= 0) then do;
                    if (missing(feature_22) or feature_22 <= 1) then do;
                        if (missing(feature_19) or feature_19 <= -1) then do;
                            treeValue4 = 0;
                        end;
                        else do;
                            treeValue4 = 0;
                        end;
                    end;
                    else do;
                        treeValue4 = 0;
                    end;
                end;
                else do;
                    if (missing(feature_13) or feature_13 <= 1) then do;
                        treeValue4 = 0;
                    end;
                    else do;
                        treeValue4 = 0;
                    end;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 1) then do;
                    if (missing(feature_24) or feature_24 <= 1) then do;
                        treeValue4 = 0;
                    end;
                    else do;
                        treeValue4 = 0;
                    end;
                end;
                else do;
                    treeValue4 = 0;
                end;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                treeValue4 = 0;
            end;
            else do;
                treeValue4 = 0;
            end;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0) then do;
            if (missing(feature_5) or feature_5 <= 0) then do;
                treeValue4 = 0;
            end;
            else do;
                treeValue4 = 0;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_26) or feature_26 <= 0) then do;
                    if (missing(feature_25) or feature_25 <= 0) then do;
                        treeValue4 = 0;
                    end;
                    else do;
                        if (missing(feature_0) or feature_0 <= 1) then do;
                            treeValue4 = 0;
                        end;
                        else do;
                            treeValue4 = 0;
                        end;
                    end;
                end;
                else do;
                    treeValue4 = 0;
                end;
            end;
            else do;
                if (missing(feature_3) or feature_3 <= 1) then do;
                    if (missing(feature_24) or feature_24 <= 1) then do;
                        if (missing(feature_22) or feature_22 <= 1) then do;
                            if (missing(feature_24) or feature_24 <= 0) then do;
                                treeValue4 = 0;
                            end;
                            else do;
                                treeValue4 = 0;
                            end;
                        end;
                        else do;
                            treeValue4 = 0;
                        end;
                    end;
                    else do;
                        treeValue4 = 0;
                    end;
                end;
                else do;
                    treeValue4 = 0;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_25) or feature_25 <= 1) then do;
        if (missing(feature_22) or feature_22 <= 1) then do;
            if (missing(feature_27) or feature_27 <= 1) then do;
                if (missing(feature_5) or feature_5 <= 1) then do;
                    treeValue4 = 0;
                end;
                else do;
                    if (missing(feature_24) or feature_24 <= 0) then do;
                        treeValue4 = 0;
                    end;
                    else do;
                        treeValue4 = 0;
                    end;
                end;
            end;
            else do;
                if (missing(feature_24) or feature_24 <= 1) then do;
                    treeValue4 = 0;
                end;
                else do;
                    treeValue4 = 0;
                end;
            end;
        end;
        else do;
            if (missing(feature_24) or feature_24 <= 1) then do;
                if (missing(feature_2) or feature_2 <= 1) then do;
                    if (missing(feature_27) or feature_27 <= 1) then do;
                        treeValue4 = 0;
                    end;
                    else do;
                        treeValue4 = 0;
                    end;
                end;
                else do;
                    treeValue4 = 0;
                end;
            end;
            else do;
                treeValue4 = 0;
            end;
        end;
    end;
    else do;
        treeValue4 = 0;
    end;
end;

/* Parsing tree 5*/
if (missing(feature_25) or feature_25 <= 1) then do;
    if (missing(feature_25) or feature_25 <= 0) then do;
        if (missing(feature_13) or feature_13 <= 0) then do;
            if (missing(feature_0) or feature_0 <= 0) then do;
                if (missing(feature_24) or feature_24 <= 0) then do;
                    if (missing(feature_22) or feature_22 <= 0) then do;
                        treeValue5 = 0;
                    end;
                    else do;
                        treeValue5 = 0;
                    end;
                end;
                else do;
                    treeValue5 = 0;
                end;
            end;
            else do;
                if (missing(feature_9) or feature_9 <= 1) then do;
                    if (missing(feature_22) or feature_22 <= 0) then do;
                        if (missing(feature_5) or feature_5 <= 1) then do;
                            treeValue5 = 0;
                        end;
                        else do;
                            treeValue5 = 0;
                        end;
                    end;
                    else do;
                        treeValue5 = 0;
                    end;
                end;
                else do;
                    treeValue5 = 0;
                end;
            end;
        end;
        else do;
            treeValue5 = 0;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0) then do;
            if (missing(feature_5) or feature_5 <= 0) then do;
                if (missing(feature_24) or feature_24 <= 0) then do;
                    treeValue5 = 0;
                end;
                else do;
                    treeValue5 = 0;
                end;
            end;
            else do;
                treeValue5 = 0;
            end;
        end;
        else do;
            if (missing(feature_25) or feature_25 <= 0) then do;
                if (missing(feature_3) or feature_3 <= 1) then do;
                    if (missing(feature_0) or feature_0 <= 1) then do;
                        if (missing(feature_5) or feature_5 <= 0) then do;
                            if (missing(feature_25) or feature_25 <= 0) then do;
                                if (missing(feature_24) or feature_24 <= 0) then do;
                                    treeValue5 = 0;
                                end;
                                else do;
                                    treeValue5 = 0;
                                end;
                            end;
                            else do;
                                treeValue5 = 0;
                            end;
                        end;
                        else do;
                            treeValue5 = 0;
                        end;
                    end;
                    else do;
                        if (missing(feature_1) or feature_1 <= 0) then do;
                            treeValue5 = 0;
                        end;
                        else do;
                            treeValue5 = 0;
                        end;
                    end;
                end;
                else do;
                    if (missing(feature_13) or feature_13 <= 0) then do;
                        treeValue5 = 0;
                    end;
                    else do;
                        treeValue5 = 0;
                    end;
                end;
            end;
            else do;
                if (missing(feature_5) or feature_5 <= 1) then do;
                    if (missing(feature_0) or feature_0 <= 0) then do;
                        treeValue5 = 0;
                    end;
                    else do;
                        if (missing(feature_26) or feature_26 <= 0) then do;
                            treeValue5 = 0;
                        end;
                        else do;
                            treeValue5 = 0;
                        end;
                    end;
                end;
                else do;
                    if (missing(feature_0) or feature_0 <= 1) then do;
                        treeValue5 = 0;
                    end;
                    else do;
                        treeValue5 = 0;
                    end;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_25) or feature_25 <= 1) then do;
        if (missing(feature_22) or feature_22 <= 1) then do;
            if (missing(feature_22) or feature_22 <= 0) then do;
                if (missing(feature_24) or feature_24 <= 1) then do;
                    treeValue5 = 0;
                end;
                else do;
                    if (missing(feature_23) or feature_23 <= 0) then do;
                        treeValue5 = 0;
                    end;
                    else do;
                        treeValue5 = 0;
                    end;
                end;
            end;
            else do;
                treeValue5 = 0;
            end;
        end;
        else do;
            treeValue5 = 0;
        end;
    end;
    else do;
        if (missing(feature_3) or feature_3 <= 1) then do;
            treeValue5 = 0;
        end;
        else do;
            treeValue5 = 0;
        end;
    end;
end;

/* Parsing tree 6*/
if (missing(feature_27) or feature_27 <= 0) then do;
    if (missing(feature_26) or feature_26 <= 0) then do;
        if (missing(feature_5) or feature_5 <= 1) then do;
            if (missing(feature_5) or feature_5 <= 0) then do;
                if (missing(feature_26) or feature_26 <= 0) then do;
                    if (missing(feature_24) or feature_24 <= 0) then do;
                        if (missing(feature_11) or feature_11 <= 0) then do;
                            treeValue6 = 0;
                        end;
                        else do;
                            treeValue6 = 0;
                        end;
                    end;
                    else do;
                        treeValue6 = 0;
                    end;
                end;
                else do;
                    treeValue6 = 0;
                end;
            end;
            else do;
                if (missing(feature_27) or feature_27 <= 0) then do;
                    treeValue6 = 0;
                end;
                else do;
                    treeValue6 = 0;
                end;
            end;
        end;
        else do;
            treeValue6 = 0;
        end;
    end;
    else do;
        if (missing(feature_5) or feature_5 <= 0) then do;
            if (missing(feature_22) or feature_22 <= 1) then do;
                if (missing(feature_0) or feature_0 <= 0) then do;
                    treeValue6 = 0;
                end;
                else do;
                    if (missing(feature_27) or feature_27 <= 0) then do;
                        treeValue6 = 0;
                    end;
                    else do;
                        if (missing(feature_26) or feature_26 <= 0) then do;
                            treeValue6 = 0;
                        end;
                        else do;
                            treeValue6 = 0;
                        end;
                    end;
                end;
            end;
            else do;
                treeValue6 = 0;
            end;
        end;
        else do;
            treeValue6 = 0;
        end;
    end;
end;
else do;
    if (missing(feature_24) or feature_24 <= 1) then do;
        if (missing(feature_22) or feature_22 <= 1) then do;
            if (missing(feature_24) or feature_24 <= 0) then do;
                if (missing(feature_27) or feature_27 <= 1) then do;
                    treeValue6 = 0;
                end;
                else do;
                    treeValue6 = 0;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 0) then do;
                    treeValue6 = 0;
                end;
                else do;
                    treeValue6 = 0;
                end;
            end;
        end;
        else do;
            if (missing(feature_26) or feature_26 <= 1) then do;
                if (missing(feature_24) or feature_24 <= 0) then do;
                    treeValue6 = 0;
                end;
                else do;
                    treeValue6 = 0;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 1) then do;
                    treeValue6 = 0;
                end;
                else do;
                    if (missing(feature_8) or feature_8 <= 1) then do;
                        treeValue6 = 0;
                    end;
                    else do;
                        treeValue6 = 0;
                    end;
                end;
            end;
        end;
    end;
    else do;
        if (missing(feature_27) or feature_27 <= 1) then do;
            if (missing(feature_9) or feature_9 <= 1) then do;
                treeValue6 = 0;
            end;
            else do;
                treeValue6 = 0;
            end;
        end;
        else do;
            if (missing(feature_24) or feature_24 <= 2) then do;
                if (missing(feature_22) or feature_22 <= 1) then do;
                    if (missing(feature_22) or feature_22 <= 0) then do;
                        treeValue6 = 0;
                    end;
                    else do;
                        if (missing(feature_13) or feature_13 <= 1) then do;
                            if (missing(feature_11) or feature_11 <= 0) then do;
                                treeValue6 = 0;
                            end;
                            else do;
                                treeValue6 = 0;
                            end;
                        end;
                        else do;
                            treeValue6 = 0;
                        end;
                    end;
                end;
                else do;
                    treeValue6 = 0;
                end;
            end;
            else do;
                if (missing(feature_1) or feature_1 <= 0) then do;
                    treeValue6 = 0;
                end;
                else do;
                    treeValue6 = 0;
                end;
            end;
        end;
    end;
end;

/* Parsing tree 7*/
if (missing(feature_25) or feature_25 <= 1) then do;
    if (missing(feature_25) or feature_25 <= 0) then do;
        if (missing(feature_5) or feature_5 <= 1) then do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_0) or feature_0 <= 0) then do;
                    if (missing(feature_13) or feature_13 <= 1) then do;
                        treeValue7 = 0;
                    end;
                    else do;
                        treeValue7 = 0;
                    end;
                end;
                else do;
                    treeValue7 = 0;
                end;
            end;
            else do;
                treeValue7 = 0;
            end;
        end;
        else do;
            treeValue7 = 0;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0) then do;
            if (missing(feature_5) or feature_5 <= 0) then do;
                treeValue7 = 0;
            end;
            else do;
                treeValue7 = 0;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_26) or feature_26 <= 0) then do;
                    if (missing(feature_25) or feature_25 <= 0) then do;
                        if (missing(feature_27) or feature_27 <= 0) then do;
                            treeValue7 = 0;
                        end;
                        else do;
                            if (missing(feature_14) or feature_14 <= 0) then do;
                                treeValue7 = 0;
                            end;
                            else do;
                                treeValue7 = 0;
                            end;
                        end;
                    end;
                    else do;
                        treeValue7 = 0;
                    end;
                end;
                else do;
                    if (missing(feature_25) or feature_25 <= 1) then do;
                        if (missing(feature_25) or feature_25 <= 0) then do;
                            treeValue7 = 0;
                        end;
                        else do;
                            treeValue7 = 0;
                        end;
                    end;
                    else do;
                        treeValue7 = 0;
                    end;
                end;
            end;
            else do;
                if (missing(feature_0) or feature_0 <= 1) then do;
                    if (missing(feature_5) or feature_5 <= 0) then do;
                        if (missing(feature_25) or feature_25 <= 0) then do;
                            if (missing(feature_26) or feature_26 <= 0) then do;
                                if (missing(feature_3) or feature_3 <= 1) then do;
                                    treeValue7 = 0;
                                end;
                                else do;
                                    treeValue7 = 0;
                                end;
                            end;
                            else do;
                                treeValue7 = 0;
                            end;
                        end;
                        else do;
                            treeValue7 = 0;
                        end;
                    end;
                    else do;
                        if (missing(feature_1) or feature_1 <= -1) then do;
                            treeValue7 = 0;
                        end;
                        else do;
                            if (missing(feature_3) or feature_3 <= 2) then do;
                                treeValue7 = 0;
                            end;
                            else do;
                                treeValue7 = 0;
                            end;
                        end;
                    end;
                end;
                else do;
                    if (missing(feature_24) or feature_24 <= 0) then do;
                        treeValue7 = 0;
                    end;
                    else do;
                        if (missing(feature_24) or feature_24 <= 1) then do;
                            if (missing(feature_5) or feature_5 <= 1) then do;
                                if (missing(feature_9) or feature_9 <= 1) then do;
                                    treeValue7 = 0;
                                end;
                                else do;
                                    treeValue7 = 0;
                                end;
                            end;
                            else do;
                                treeValue7 = 0;
                            end;
                        end;
                        else do;
                            treeValue7 = 0;
                        end;
                    end;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_3) or feature_3 <= 1) then do;
        if (missing(feature_25) or feature_25 <= 1) then do;
            if (missing(feature_5) or feature_5 <= 0) then do;
                if (missing(feature_23) or feature_23 <= 1) then do;
                    treeValue7 = 0;
                end;
                else do;
                    treeValue7 = 0;
                end;
            end;
            else do;
                treeValue7 = 0;
            end;
        end;
        else do;
            treeValue7 = 0;
        end;
    end;
    else do;
        treeValue7 = 0;
    end;
end;

/* Parsing tree 8*/
if (missing(feature_25) or feature_25 <= 1) then do;
    if (missing(feature_25) or feature_25 <= 0) then do;
        if (missing(feature_5) or feature_5 <= 1) then do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_9) or feature_9 <= 1) then do;
                    if (missing(feature_3) or feature_3 <= 0) then do;
                        treeValue8 = 0;
                    end;
                    else do;
                        if (missing(feature_0) or feature_0 <= 1) then do;
                            if (missing(feature_13) or feature_13 <= 1) then do;
                                treeValue8 = 0;
                            end;
                            else do;
                                treeValue8 = 0;
                            end;
                        end;
                        else do;
                            treeValue8 = 0;
                        end;
                    end;
                end;
                else do;
                    treeValue8 = 0;
                end;
            end;
            else do;
                if (missing(feature_2) or feature_2 <= 1) then do;
                    if (missing(feature_2) or feature_2 <= 0) then do;
                        treeValue8 = 0;
                    end;
                    else do;
                        treeValue8 = 0;
                    end;
                end;
                else do;
                    treeValue8 = 0;
                end;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                treeValue8 = 0;
            end;
            else do;
                treeValue8 = 0;
            end;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0) then do;
            if (missing(feature_5) or feature_5 <= 0) then do;
                treeValue8 = 0;
            end;
            else do;
                treeValue8 = 0;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_26) or feature_26 <= 0) then do;
                    if (missing(feature_27) or feature_27 <= 0) then do;
                        if (missing(feature_25) or feature_25 <= 0) then do;
                            treeValue8 = 0;
                        end;
                        else do;
                            treeValue8 = 0;
                        end;
                    end;
                    else do;
                        treeValue8 = 0;
                    end;
                end;
                else do;
                    treeValue8 = 0;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 1) then do;
                    if (missing(feature_0) or feature_0 <= 0) then do;
                        if (missing(feature_18) or feature_18 <= 1) then do;
                            treeValue8 = 0;
                        end;
                        else do;
                            treeValue8 = 0;
                        end;
                    end;
                    else do;
                        if (missing(feature_27) or feature_27 <= 1) then do;
                            if (missing(feature_22) or feature_22 <= 0) then do;
                                treeValue8 = 0;
                            end;
                            else do;
                                treeValue8 = 0;
                            end;
                        end;
                        else do;
                            treeValue8 = 0;
                        end;
                    end;
                end;
                else do;
                    treeValue8 = 0;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_25) or feature_25 <= 1) then do;
        if (missing(feature_22) or feature_22 <= 1) then do;
            if (missing(feature_22) or feature_22 <= 0) then do;
                if (missing(feature_13) or feature_13 <= 0) then do;
                    treeValue8 = 0;
                end;
                else do;
                    if (missing(feature_9) or feature_9 <= 0) then do;
                        treeValue8 = 0;
                    end;
                    else do;
                        treeValue8 = 0;
                    end;
                end;
            end;
            else do;
                if (missing(feature_27) or feature_27 <= 0) then do;
                    if (missing(feature_5) or feature_5 <= 1) then do;
                        treeValue8 = 0;
                    end;
                    else do;
                        treeValue8 = 0;
                    end;
                end;
                else do;
                    treeValue8 = 0;
                end;
            end;
        end;
        else do;
            treeValue8 = 0;
        end;
    end;
    else do;
        if (missing(feature_3) or feature_3 <= 1) then do;
            treeValue8 = 0;
        end;
        else do;
            treeValue8 = 0;
        end;
    end;
end;

/* Parsing tree 9*/
if (missing(feature_25) or feature_25 <= 1) then do;
    if (missing(feature_25) or feature_25 <= 0) then do;
        if (missing(feature_13) or feature_13 <= 0) then do;
            if (missing(feature_9) or feature_9 <= 1) then do;
                treeValue9 = 0;
            end;
            else do;
                treeValue9 = 0;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_25) or feature_25 <= 0) then do;
                    treeValue9 = 0;
                end;
                else do;
                    treeValue9 = 0;
                end;
            end;
            else do;
                treeValue9 = 0;
            end;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0) then do;
            if (missing(feature_5) or feature_5 <= 0) then do;
                if (missing(feature_24) or feature_24 <= 0) then do;
                    treeValue9 = 0;
                end;
                else do;
                    if (missing(feature_19) or feature_19 <= -1) then do;
                        treeValue9 = 0;
                    end;
                    else do;
                        treeValue9 = 0;
                    end;
                end;
            end;
            else do;
                treeValue9 = 0;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0) then do;
                if (missing(feature_26) or feature_26 <= 0) then do;
                    if (missing(feature_25) or feature_25 <= 0) then do;
                        if (missing(feature_27) or feature_27 <= 0) then do;
                            treeValue9 = 0;
                        end;
                        else do;
                            treeValue9 = 0;
                        end;
                    end;
                    else do;
                        treeValue9 = 0;
                    end;
                end;
                else do;
                    if (missing(feature_25) or feature_25 <= 1) then do;
                        if (missing(feature_25) or feature_25 <= 0) then do;
                            treeValue9 = 0;
                        end;
                        else do;
                            if (missing(feature_5) or feature_5 <= 0) then do;
                                treeValue9 = 0;
                            end;
                            else do;
                                treeValue9 = 0;
                            end;
                        end;
                    end;
                    else do;
                        treeValue9 = 0;
                    end;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 1) then do;
                    if (missing(feature_24) or feature_24 <= 0) then do;
                        if (missing(feature_24) or feature_24 <= 0) then do;
                            treeValue9 = 0;
                        end;
                        else do;
                            treeValue9 = 0;
                        end;
                    end;
                    else do;
                        treeValue9 = 0;
                    end;
                end;
                else do;
                    if (missing(feature_5) or feature_5 <= 1) then do;
                        treeValue9 = 0;
                    end;
                    else do;
                        treeValue9 = 0;
                    end;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_3) or feature_3 <= 1) then do;
        if (missing(feature_24) or feature_24 <= 1) then do;
            if (missing(feature_25) or feature_25 <= 2) then do;
                if (missing(feature_24) or feature_24 <= 0) then do;
                    treeValue9 = 0;
                end;
                else do;
                    if (missing(feature_15) or feature_15 <= -1) then do;
                        treeValue9 = 0;
                    end;
                    else do;
                        if (missing(feature_22) or feature_22 <= 0) then do;
                            treeValue9 = 0;
                        end;
                        else do;
                            if (missing(feature_22) or feature_22 <= 0) then do;
                                treeValue9 = 0;
                            end;
                            else do;
                                treeValue9 = 0;
                            end;
                        end;
                    end;
                end;
            end;
            else do;
                treeValue9 = 0;
            end;
        end;
        else do;
            if (missing(feature_1) or feature_1 <= 1) then do;
                if (missing(feature_11) or feature_11 <= 0) then do;
                    treeValue9 = 0;
                end;
                else do;
                    treeValue9 = 0;
                end;
            end;
            else do;
                treeValue9 = 0;
            end;
        end;
    end;
    else do;
        treeValue9 = 0;
    end;
end;

/* Getting target probability */
treeValue = sum(treeValue0, treeValue1, treeValue2, treeValue3, treeValue4, treeValue5, treeValue6, treeValue7, treeValue8, treeValue9);
P_TARGET = 1 / (1 + exp(-treeValue));
